import { ActionRowBuilder, ButtonBuilder, ButtonStyle, Client, EmbedBuilder, Events, GatewayIntentBits, PermissionFlagsBits, REST, Routes, SlashCommandBuilder, StringSelectMenuBuilder } from 'discord.js';
import { initDatabase } from './database.js';
import { GAME, SPECIES } from './config.js';
import { activePet, adopt, balanceChange, buy, care, claimDaily, equip, getUser, petById, petsOf, rename, rewardMessage, setActive, unequip } from './game.js';
import { dressingHome, dressingItem, petPayload, pinkHomePayload, profilePayload, shopItemPayload, welcomePayload } from './ui.js';

const commands=[
 new SlashCommandBuilder().setName('commencer').setDescription('Créer ton profil BalekPets et choisir ton premier animal.'),
 new SlashCommandBuilder().setName('animal').setDescription('Afficher et gérer ton animal actif.'),
 new SlashCommandBuilder().setName('elevage').setDescription('Ouvrir l’élevage de Julien & Miky.'),
 new SlashCommandBuilder().setName('pink').setDescription('Ouvrir la boutique Pink Studio.'),
 new SlashCommandBuilder().setName('journalier').setDescription('Récupérer 200 Balekium.'),
 new SlashCommandBuilder().setName('profil').setDescription('Voir un profil BalekPets.').addUserOption(o=>o.setName('membre').setDescription('Membre à consulter')),
 new SlashCommandBuilder().setName('renommer').setDescription('Renommer ton animal actif.').addStringOption(o=>o.setName('nom').setDescription('Nouveau nom').setRequired(true).setMinLength(2).setMaxLength(24)),
 new SlashCommandBuilder().setName('balekium').setDescription('Afficher ton solde.'),
 new SlashCommandBuilder().setName('admin-balekium').setDescription('Définir le solde d’un membre ou d’un rôle.').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addIntegerOption(o=>o.setName('montant').setDescription('Nouveau solde').setRequired(true).setMinValue(0)).addUserOption(o=>o.setName('membre').setDescription('Membre à cibler')).addRoleOption(o=>o.setName('role').setDescription('Rôle à cibler'))
].map(c=>c.toJSON());

async function deploy(){ const token=process.env.DISCORD_TOKEN,id=process.env.CLIENT_ID,guild=process.env.GUILD_ID; if(!id||!guild)return console.warn('[BalekPets] CLIENT_ID ou GUILD_ID absent, commandes non redéployées.'); await new REST({version:'10'}).setToken(token).put(Routes.applicationGuildCommands(id,guild),{body:commands}); console.log(`[BalekPets] ${commands.length} commandes déployées.`); }
const replace=(p)=>({...p,attachments:[]});
const visible=(content)=>({content});
function setBalance(userId, amount, reason) {
 const current=getUser(userId).balance;
 balanceChange(userId,amount-current,reason);
}
function nursery(){ const e=new EmbedBuilder().setColor(0x8fd09d).setTitle('🌿 Élevage de Juju & Miky').setDescription('Adopte un nouveau compagnon. Le premier animal doit être choisi avec `/commencer`.').addFields(Object.values(SPECIES).map(s=>({name:`${s.emoji} ${s.name}`,value:s.unavailable?`Bientôt disponible · gamme ${s.price} ${GAME.currency}`:`${s.price} ${GAME.currency} · ${s.description}`,inline:false}))); const menu=new StringSelectMenuBuilder().setCustomId('nursery').setPlaceholder('Choisir un animal à adopter').addOptions(Object.values(SPECIES).map(s=>({label:s.name,value:s.id,emoji:s.emoji,description:s.unavailable?'Bientôt disponible':`${s.price} ${GAME.currency}`,default:false}))); return {embeds:[e],components:[new ActionRowBuilder().addComponents(menu)]}; }
export async function startBot(){ const token=process.env.DISCORD_TOKEN;if(!token)throw new Error('DISCORD_TOKEN absent du fichier .env'); initDatabase(process.env.DATABASE_PATH??'./data/balekpets.sqlite'); await deploy(); const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMessages,GatewayIntentBits.GuildMembers]}); client.once(Events.ClientReady,c=>console.log(`[BalekPets] Connecté en tant que ${c.user.tag}`)); client.on(Events.MessageCreate,m=>{if(m.inGuild()&&!m.author.bot)rewardMessage(m.author.id);}); client.on(Events.InteractionCreate,async i=>{try{if(i.isChatInputCommand())await command(i);else if(i.isStringSelectMenu())await select(i);else if(i.isButton())await button(i);}catch(e){console.error('[BalekPets] Interaction:',e);const p=visible('Une anomalie a traversé la Zone du Silence. Regarde la console.');if(i.replied||i.deferred)await i.followUp(p).catch(()=>{});else await i.reply(p).catch(()=>{});}}); await client.login(token); }
async function command(i){ const id=i.user.id; if(i.commandName==='commencer'){if(petsOf(id).length)return i.reply(visible('Ton élevage existe déjà. Utilise `/animal`.'));return i.reply(welcomePayload(id));} if(i.commandName==='animal'){const p=activePet(id);return p?i.reply(await petPayload(p,i.member??i.user)):i.reply(visible('Tu n’as pas encore commencé BalekPets. Utilise d’abord `/commencer` pour choisir ton premier compagnon.'));} if(i.commandName==='elevage')return i.reply(nursery()); if(i.commandName==='pink'){const p=activePet(id);return p?i.reply(pinkHomePayload(p.species_id,p.id)):i.reply(visible('Tu n’as pas encore commencé BalekPets. Utilise d’abord `/commencer`.'));} if(i.commandName==='journalier'){const r=claimDaily(id);return i.reply(visible(r.ok?`✅ 200 Balekium reçus. Solde : **${r.balance}**.`:`Reviens dans **${Math.ceil(r.remaining/3600000)} h**.`));} if(i.commandName==='balekium')return i.reply(visible(`Tu possèdes **${getUser(id).balance} Balekium**.`)); if(i.commandName==='renommer'){const name=i.options.getString('nom',true).trim();return i.reply(visible(rename(id,name)?`Ton animal s’appelle maintenant **${name}**.`:'Aucun animal actif.'));} if(i.commandName==='profil'){const u=i.options.getUser('membre')??i.user;return i.reply(await profilePayload(u,petsOf(u.id),0));} if(i.commandName==='admin-balekium'){const amount=i.options.getInteger('montant',true),u=i.options.getUser('membre'),role=i.options.getRole('role');if((u&&role)||(!u&&!role))return i.reply(visible('Choisis **un membre** ou **un rôle**, mais pas les deux.'));if(u){setBalance(u.id,amount,`admin:${i.user.id}`);return i.reply(visible(`Solde de ${u} défini à **${amount} Balekium**.`));}await i.guild.members.fetch();const members=role.members.filter(m=>!m.user.bot);for(const member of members.values())setBalance(member.id,amount,`admin-role:${role.id}:${i.user.id}`);return i.reply(visible(`Solde défini à **${amount} Balekium** pour **${members.size} membre(s)** du rôle ${role}.`));}}
async function select(i){const id=i.user.id,[a,ownerOrPet]=i.customId.split(':');if(a==='starter'){if(ownerOrPet!==id)return i.reply(visible(`Ce choix appartient à <@${ownerOrPet}>. Utilise \`/commencer\` pour créer ton propre élevage.`));const r=adopt(id,i.values[0],true);return i.update({content:r.ok?`🎉 **${r.pet.name}** rejoint l’élevage de <@${id}> ! Utilise maintenant \`/animal\`.`:'Adoption impossible.',embeds:[],components:[]});} if(a==='pink_species')return i.update({...pinkHomePayload(i.values[0],ownerOrPet||null),attachments:[]}); if(i.customId==='nursery'){const sp=SPECIES[i.values[0]];const e=new EmbedBuilder().setColor(0x8fd09d).setTitle(`${sp.emoji} ${sp.name}`).setDescription(sp.description).addFields({name:'Prix',value:sp.unavailable?'Bientôt disponible':`${sp.price} Balekium`});const b=new ButtonBuilder().setCustomId(`adopt:${sp.id}`).setLabel(sp.unavailable?'Indisponible':`Adopter · ${sp.price}`).setDisabled(Boolean(sp.unavailable)).setStyle(ButtonStyle.Success);return i.update({embeds:[e],components:[new ActionRowBuilder().addComponents(b)]});} if(i.customId.startsWith('switchpet:')){const owner=i.customId.split(':')[1];if(owner!==id)return i.reply(visible(`Ce menu appartient à <@${owner}>. Utilise \`/animal\` pour gérer ton BalekPet.`));setActive(id,Number(i.values[0]));const p=activePet(id);return i.update(replace(await petPayload(p,i.member??i.user)));}}
async function button(i){
 const [a,...p]=i.customId.split(':'),id=i.user.id;
 const ownedPet=(petId)=>{const pet=petById(Number(petId));return pet&&pet.user_id===id?pet:null;};
 const ownerWarning=async(petId)=>{
  const pet=petById(Number(petId));
  if(!pet)return 'Ce BalekPet est introuvable.';
  const owner=await i.client.users.fetch(pet.user_id).catch(()=>null);
  return `Ce BalekPet appartient à **${owner?.displayName??owner?.username??'un autre membre'}**. Utilise \`/animal\` pour gérer le tien.`;
 };
 if(a==='pink_home'){const pet=ownedPet(p[0]);if(!pet)return i.reply(visible(await ownerWarning(p[0])));return i.reply({...pinkHomePayload(pet.species_id,pet.id)});}
 if(a==='back_animal'){const pet=ownedPet(p[0]);return pet?i.update(replace(await petPayload(pet,i.member??i.user))):i.reply(visible(await ownerWarning(p[0])));}
 if(a==='pink')return i.update({...pinkHomePayload(p[0],p[1]||null),attachments:[]});
 if(a==='shop')return i.update(replace(await shopItemPayload(id,p[0],p[1],Number(p[2]),undefined,p[3]||null)));
 if(a==='buy'){const r=buy(id,p[3]);const msg=r.ok?`✅ **${r.item.name}** acheté. Solde : **${r.balance}**.`:r.reason==='funds'?'❌ Pas assez de Balekium.':'Tu possèdes déjà cet article.';return i.update(replace(await shopItemPayload(id,p[0],p[1],Number(p[2]),msg,p[4]||null)));}
 if(a==='adopt'){const r=adopt(id,p[0],false);const msg={owned:'Tu possèdes déjà cette espèce.',funds:'Pas assez de Balekium.',start_first:'Utilise d’abord `/commencer`.',unavailable:'Cette espèce arrive bientôt.'}[r.reason];return r.ok?i.update({content:`🎉 **${r.pet.name}** rejoint ta collection. Solde : **${r.balance}**.`,embeds:[],components:[]}):i.reply(visible(msg??'Adoption impossible.'));}
 if(a==='care'){const r=care(id,Number(p[1]),p[0],false);if(!r.ok)return i.reply(visible(r.reason==='owner'?await ownerWarning(p[1]):r.reason==='cooldown'?`Action disponible dans ${Math.ceil(r.remaining/60000)} min.`:'Action impossible.'));return i.update(replace(await petPayload(r.pet,i.member??i.user,`✅ Soin effectué, +${r.gainedXp} XP.`)));}
 if(a==='express'){const pet=ownedPet(p[0]);if(!pet)return i.reply(visible(await ownerWarning(p[0])));const row=new ActionRowBuilder().addComponents(['food','happiness','vitality'].map(t=>new ButtonBuilder().setCustomId(`expresscare:${t}:${pet.id}`).setLabel(`${t==='food'?'Nourriture':t==='happiness'?'Bonheur':'Vitalité'} +10 · 50`).setStyle(ButtonStyle.Secondary)));return i.reply({content:'Soins express sans délai · **+3 XP uniquement si la jauge n’est pas pleine** :',components:[row]});}
 if(a==='expresscare'){const r=care(id,Number(p[1]),p[0],true);return i.reply(visible(r.ok?`✅ Soin express effectué, +${r.gainedXp} XP. Solde : **${r.balance}**.`:r.reason==='full'?'Cette jauge est déjà pleine : aucun Balekium dépensé et aucun XP gagné.':r.reason==='funds'?'Pas assez de Balekium.':r.reason==='owner'?await ownerWarning(p[1]):'Action impossible.'));}
 if(a==='dress'){const pet=ownedPet(p[0]);if(!pet)return i.reply(visible(await ownerWarning(p[0])));return i.reply({...dressingHome(pet)});}
 if(a==='dressslot'){const pet=ownedPet(p[0]);if(!pet)return i.reply(visible(await ownerWarning(p[0])));return i.update(replace(await dressingItem(id,pet,p[1],Number(p[2]))));}
 if(a==='equip'){const petId=Number(p[0]),slot=p[1],index=Number(p[2]),itemId=p[3];const r=itemId==='none'?unequip(id,petId,slot):equip(id,petId,itemId);return i.update(replace(await dressingItem(id,r.pet??petById(petId),slot,index,r.ok?'✅ Apparence mise à jour.':'Modification impossible.')));}
 if(a==='switch'){const pet=ownedPet(p[0]);if(!pet)return i.reply(visible(await ownerWarning(p[0])));const ps=petsOf(id);if(ps.length<2)return i.reply(visible('Tu ne possèdes qu’un seul animal.'));const menu=new StringSelectMenuBuilder().setCustomId(`switchpet:${id}`).setPlaceholder('Choisir l’animal actif').addOptions(ps.map(x=>({label:`${x.name} · ${SPECIES[x.species_id].name}`,value:String(x.id),default:Boolean(x.is_active)})));return i.reply({content:'Choisis ton animal actif :',components:[new ActionRowBuilder().addComponents(menu)]});}
 if(a==='profile'){const u=await i.client.users.fetch(p[0]);return i.update(replace(await profilePayload(u,petsOf(u.id),Number(p[1]))));}
}
