import { ActionRowBuilder, AttachmentBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder, StringSelectMenuBuilder } from 'discord.js';
import { GAME, SPECIES, SLOT_DEFS } from './config.js';
import { getItem, getShopItems } from './catalog.js';
import { getUser, owned, ownedItems } from './game.js';
import { renderPet, renderPreview } from './render.js';

const bar=(v)=>`${'▰'.repeat(Math.round(v/10))}${'▱'.repeat(10-Math.round(v/10))} ${v}/100`;
export function welcomePayload(userId){
 const embed=new EmbedBuilder().setColor(0xff77b7).setTitle('✨ Bienvenue dans BalekPets').setDescription('Adopte ton premier compagnon, prends-en soin et crée ses tenues dans l’univers des Baleks.').addFields({name:'Ton premier élevage',value:'Choisis gratuitement un **Cocobalek** ou un **Buffalek**.'},{name:'Ensuite',value:'Utilise `/animal`, gagne du Balekium, visite **Pink Studio** et adopte de nouveaux compagnons chez **Juju & Miky**.'}).setFooter({text:'Le Balekium se gagne en discutant et avec /journalier.'});
 const menu=new StringSelectMenuBuilder().setCustomId(`starter:${userId}`).setPlaceholder('Choisir mon premier BalekPet').addOptions(Object.values(SPECIES).filter(s=>s.starter).map(s=>({label:s.name,value:s.id,emoji:s.emoji,description:s.description})));
 return {embeds:[embed],components:[new ActionRowBuilder().addComponents(menu)]};
}
export async function petPayload(pet,owner,notice){ const file=`animal-${pet.id}.png`,img=await renderPet(pet); const sp=SPECIES[pet.species_id]; const appearance=(SLOT_DEFS[pet.species_id]??[]).map(d=>`${d.emoji} ${d.label} : **${getItem(pet[d.column])?.name??'Aucun'}**`).join('\n'); const e=new EmbedBuilder().setColor(0xff77b7).setAuthor({name:`Élevage de ${owner.displayName??owner.username}`,iconURL:owner.displayAvatarURL?.()}).setTitle(`${sp.emoji} ${pet.name} · ${sp.name}`).setDescription(notice??'Ton compagnon t’attend.').addFields({name:'🍕 Nourriture',value:bar(pet.food)},{name:'💗 Bonheur',value:bar(pet.happiness)},{name:'✨ Vitalité',value:bar(pet.vitality)},{name:'📈 Progression',value:`Niveau **${pet.level}** · XP **${pet.xp}/${pet.level*100}**`,inline:true},{name:'🎂 Âge',value:`${Math.floor((Date.now()-pet.adopted_at)/86400000)} jour(s)`,inline:true},{name:'🎨 Apparence',value:`🏞️ Lieu : **${getItem(pet.location_id)?.name??'Burrata Academy'}**\n${appearance||'Aucun équipement'}`}).setImage(`attachment://${file}`).setFooter({text:'Le BalekPet occupe 75 % du décor.'});
 const r1=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`care:food:${pet.id}`).setLabel('Nourrir').setEmoji('🍕').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`care:happiness:${pet.id}`).setLabel('Câlin').setEmoji('💗').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`care:vitality:${pet.id}`).setLabel('Repos').setEmoji('🌙').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`express:${pet.id}`).setLabel('Express').setEmoji('⚡').setStyle(ButtonStyle.Danger));
 const r2=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`dress:${pet.id}`).setLabel('Dressing').setEmoji('👗').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`switch:${pet.id}`).setLabel('Changer d’animal').setEmoji('🐾').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`pink_home:${pet.id}`).setLabel('Pink Studio').setEmoji('🛍️').setStyle(ButtonStyle.Primary));
 return {embeds:[e],components:[r1,r2],files:[new AttachmentBuilder(img,{name:file})]}; }
export function pinkHomePayload(species='cocobalek',petId=null){ const sp=SPECIES[species]; const e=new EmbedBuilder().setColor(0xff69b4).setTitle('🛍️ Boutique Pink Studio').setDescription(`Collection actuelle : **${sp.name}**\nChoisis une catégorie. Les articles achetés apparaissent immédiatement dans le dressing.`).addFields({name:'Solde',value:'Ton solde est affiché dans chaque fiche article.'}); const speciesMenu=new StringSelectMenuBuilder().setCustomId(`pink_species:${petId??''}`).setPlaceholder('Choisir la boutique de l’animal').addOptions(['cocobalek','buffalek','volpek'].map(id=>({label:SPECIES[id].name,value:id,emoji:SPECIES[id].emoji,default:id===species}))); const defs=[...(SLOT_DEFS[species]??[]),{id:'lieu',label:'Lieux',emoji:'🏞️'}]; const rows=[new ActionRowBuilder().addComponents(speciesMenu),new ActionRowBuilder().addComponents(defs.map(d=>new ButtonBuilder().setCustomId(`shop:${species}:${d.id}:0:${petId??''}`).setLabel(d.label).setEmoji(d.emoji).setStyle(ButtonStyle.Secondary)))]; if(petId)rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`back_animal:${petId}`).setLabel('Retour à mon animal').setEmoji('🐾').setStyle(ButtonStyle.Primary))); return {embeds:[e],components:rows}; }
export async function shopItemPayload(userId,species,slot,index,notice,petId=null){ const items=getShopItems(species,slot); if(!items.length)return pinkHomePayload(species,petId); index=((Number(index)%items.length)+items.length)%items.length; const item=items[index],file=`shop-${item.id}.png`,img=await renderPreview(species,item),user=getUser(userId),has=owned(userId,item.id); const e=new EmbedBuilder().setColor(0xff69b4).setTitle(`${item.name}`).setDescription(notice??`Article pour **${SPECIES[species].name}**`).addFields({name:'Prix',value:`${item.price} ${GAME.currency}`,inline:true},{name:'Ton solde',value:`${user.balance} ${GAME.currency}`,inline:true},{name:'État',value:has?'✅ Déjà possédé':'🛒 Disponible',inline:true}).setImage(`attachment://${file}`).setFooter({text:`${index+1}/${items.length} · Boutique ${SPECIES[species].name}`}); const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`shop:${species}:${slot}:${index-1}:${petId??''}`).setEmoji('⬅️').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`buy:${species}:${slot}:${index}:${item.id}:${petId??''}`).setLabel(has?'Possédé':`Acheter · ${item.price}`).setDisabled(has).setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`shop:${species}:${slot}:${index+1}:${petId??''}`).setEmoji('➡️').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`pink:${species}:${petId??''}`).setLabel('Catégories').setStyle(ButtonStyle.Primary)); return {embeds:[e],components:[row],files:[new AttachmentBuilder(img,{name:file})]}; }
export async function profilePayload(user,pets,index=0){
 if(!pets.length){const e=new EmbedBuilder().setColor(0xb68cff).setTitle(`Profil BalekPets de ${user.displayName}`).setThumbnail(user.displayAvatarURL()).setDescription('Aucun animal dans cet élevage.');return {embeds:[e],components:[]};}
 const ordered=[...pets].sort((a,b)=>Number(b.is_active)-Number(a.is_active)),pet=ordered[((index%ordered.length)+ordered.length)%ordered.length],sp=SPECIES[pet.species_id],file=`profil-${user.id}-${pet.id}.png`,img=await renderPet(pet);
 const equipped=(SLOT_DEFS[pet.species_id]??[]).map(d=>getItem(pet[d.column])?.name).filter(Boolean);
 const e=new EmbedBuilder().setColor(0xb68cff).setAuthor({name:`Collection de ${user.displayName}`,iconURL:user.displayAvatarURL()}).setTitle(`${pet.is_active?'⭐ ':''}${pet.name} · ${sp.name}`).setDescription(`${pet.is_active?'Animal actif · ':''}Niveau **${pet.level}** · XP **${pet.xp}/${pet.level*100}**`).addFields({name:'Balekium',value:String(getUser(user.id).balance),inline:true},{name:'Animaux possédés',value:String(ordered.length),inline:true},{name:'Tenue actuelle',value:equipped.length?equipped.join(' · '):'Apparence classique'},{name:'Collection',value:`Animal **${ordered.indexOf(pet)+1}/${ordered.length}**`}).setImage(`attachment://${file}`).setFooter({text:'Utilise les flèches pour voir chaque animal séparément.'});
 const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`profile:${user.id}:${index-1}`).setEmoji('⬅️').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`profile:${user.id}:${index+1}`).setEmoji('➡️').setStyle(ButtonStyle.Secondary));
 return {embeds:[e],components:[row],files:[new AttachmentBuilder(img,{name:file})]};
}
export function dressingHome(pet){ const defs=[...(SLOT_DEFS[pet.species_id]??[]),{id:'lieu',label:'Lieu',emoji:'🏞️'}]; const e=new EmbedBuilder().setColor(0xb68cff).setTitle(`👗 Dressing de ${pet.name}`).setDescription('Choisis une catégorie, puis parcours les objets possédés avec les flèches.'); return {embeds:[e],components:[new ActionRowBuilder().addComponents(defs.map(d=>new ButtonBuilder().setCustomId(`dressslot:${pet.id}:${d.id}:0`).setLabel(d.label).setEmoji(d.emoji).setStyle(ButtonStyle.Secondary)))]}; }
export async function dressingItem(userId,pet,slot,index,notice){ let items=ownedItems(userId,pet.species_id,slot); const allowNone=slot!=='tenue'&&slot!=='lieu'; if(allowNone)items=[{id:'none',name:'Aucun',slot},...items]; if(!items.length)return dressingHome(pet); index=((Number(index)%items.length)+items.length)%items.length; const item=items[index],preview={[slot]:item.id==='none'?null:item.id},file=`dress-${pet.id}-${slot}.png`,img=await renderPet(pet,preview); const e=new EmbedBuilder().setColor(0xb68cff).setTitle(`${item.name}`).setDescription(notice??'Aperçu avant équipement.').setImage(`attachment://${file}`).setFooter({text:`${index+1}/${items.length}`}); const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`dressslot:${pet.id}:${slot}:${index-1}`).setEmoji('⬅️').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`equip:${pet.id}:${slot}:${index}:${item.id}`).setLabel(item.id==='none'?'Retirer':'Équiper').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`dressslot:${pet.id}:${slot}:${index+1}`).setEmoji('➡️').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`dress:${pet.id}`).setLabel('Retour').setStyle(ButtonStyle.Primary)); return {embeds:[e],components:[row],files:[new AttachmentBuilder(img,{name:file})]}; }
